In [1]:
#IMPORT LIBRARIES
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt


In [2]:
#creating a random data using numpy array
rand_data = 283 + 5 * np.random.randn(5,3,4)
rand_data

array([[[275.12509039, 269.41061548, 283.97902461, 281.51688821],
        [278.67992698, 287.9011431 , 277.78258109, 280.42853622],
        [282.36924659, 284.81747578, 284.54612879, 286.48135453]],

       [[285.18633817, 284.11868164, 283.11520095, 285.8536749 ],
        [280.76044676, 288.19108802, 275.78053168, 283.22108938],
        [276.09858054, 275.86464566, 290.73818937, 294.44051927]],

       [[277.08265618, 275.52299133, 286.09677439, 291.89696028],
        [282.24515044, 278.96829929, 283.56997916, 276.43534198],
        [279.81312193, 282.21178967, 278.2288655 , 284.56146436]],

       [[283.07669505, 287.43909443, 278.23173183, 280.48565225],
        [287.70152491, 278.46032733, 290.3711811 , 279.88530479],
        [291.15794986, 284.56061581, 285.73853555, 278.69044711]],

       [[280.24841229, 279.76893218, 281.8246932 , 288.74111035],
        [279.0226259 , 281.80205068, 279.5120701 , 285.82918359],
        [282.0789096 , 275.44621061, 293.99793949, 283.27026802]]])

In [3]:
#wrap the array 
temperature = xr.DataArray(rand_data)
temperature

<xarray.DataArray (dim_0: 5, dim_1: 3, dim_2: 4)> Size: 480B
array([[[275.12509039, 269.41061548, 283.97902461, 281.51688821],
        [278.67992698, 287.9011431 , 277.78258109, 280.42853622],
        [282.36924659, 284.81747578, 284.54612879, 286.48135453]],

       [[285.18633817, 284.11868164, 283.11520095, 285.8536749 ],
        [280.76044676, 288.19108802, 275.78053168, 283.22108938],
        [276.09858054, 275.86464566, 290.73818937, 294.44051927]],

       [[277.08265618, 275.52299133, 286.09677439, 291.89696028],
        [282.24515044, 278.96829929, 283.56997916, 276.43534198],
        [279.81312193, 282.21178967, 278.2288655 , 284.56146436]],

       [[283.07669505, 287.43909443, 278.23173183, 280.48565225],
        [287.70152491, 278.46032733, 290.3711811 , 279.88530479],
        [291.15794986, 284.56061581, 285.73853555, 278.69044711]],

       [[280.24841229, 279.76893218, 281.8246932 , 288.74111035],
        [279.0226259 , 281.80205068, 279.5120701 , 285.82918359],
        [282.0789096 , 275.44621061, 293.99793949, 283.27026802]]])
Dimensions without coordinates: dim_0, dim_1, dim_2

In [4]:
#assingning dimension names
temperature = xr.DataArray(rand_data,dims=["time","lat","lon"])
temperature

<xarray.DataArray (time: 5, lat: 3, lon: 4)> Size: 480B
array([[[275.12509039, 269.41061548, 283.97902461, 281.51688821],
        [278.67992698, 287.9011431 , 277.78258109, 280.42853622],
        [282.36924659, 284.81747578, 284.54612879, 286.48135453]],

       [[285.18633817, 284.11868164, 283.11520095, 285.8536749 ],
        [280.76044676, 288.19108802, 275.78053168, 283.22108938],
        [276.09858054, 275.86464566, 290.73818937, 294.44051927]],

       [[277.08265618, 275.52299133, 286.09677439, 291.89696028],
        [282.24515044, 278.96829929, 283.56997916, 276.43534198],
        [279.81312193, 282.21178967, 278.2288655 , 284.56146436]],

       [[283.07669505, 287.43909443, 278.23173183, 280.48565225],
        [287.70152491, 278.46032733, 290.3711811 , 279.88530479],
        [291.15794986, 284.56061581, 285.73853555, 278.69044711]],

       [[280.24841229, 279.76893218, 281.8246932 , 288.74111035],
        [279.0226259 , 281.80205068, 279.5120701 , 285.82918359],
        [282.0789096 , 275.44621061, 293.99793949, 283.27026802]]])
Dimensions without coordinates: time, lat, lon

In [5]:
times_index = pd.date_range("2018-01-01",periods=5)
times_index

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[us]', freq='D')

In [6]:
lons = np.linspace(-120,-60,4)
lats = np.linspace(25,55,3)

In [7]:
temperature = xr.DataArray(
    rand_data,coords=[times_index,lats,lons],dims=["time","lat","lons"]
)
temperature

<xarray.DataArray (time: 5, lat: 3, lons: 4)> Size: 480B
array([[[275.12509039, 269.41061548, 283.97902461, 281.51688821],
        [278.67992698, 287.9011431 , 277.78258109, 280.42853622],
        [282.36924659, 284.81747578, 284.54612879, 286.48135453]],

       [[285.18633817, 284.11868164, 283.11520095, 285.8536749 ],
        [280.76044676, 288.19108802, 275.78053168, 283.22108938],
        [276.09858054, 275.86464566, 290.73818937, 294.44051927]],

       [[277.08265618, 275.52299133, 286.09677439, 291.89696028],
        [282.24515044, 278.96829929, 283.56997916, 276.43534198],
        [279.81312193, 282.21178967, 278.2288655 , 284.56146436]],

       [[283.07669505, 287.43909443, 278.23173183, 280.48565225],
        [287.70152491, 278.46032733, 290.3711811 , 279.88530479],
        [291.15794986, 284.56061581, 285.73853555, 278.69044711]],

       [[280.24841229, 279.76893218, 281.8246932 , 288.74111035],
        [279.0226259 , 281.80205068, 279.5120701 , 285.82918359],
        [282.0789096 , 275.44621061, 293.99793949, 283.27026802]]])
Coordinates:
  * time     (time) datetime64[us] 40B 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 24B 25.0 40.0 55.0
  * lons     (lons) float64 32B -120.0 -100.0 -80.0 -60.0

In [8]:
temperature.attrs["units"] = "Kelvin"
temperature.attrs["standard_name"]="air_temperature"
temperature

<xarray.DataArray (time: 5, lat: 3, lons: 4)> Size: 480B
array([[[275.12509039, 269.41061548, 283.97902461, 281.51688821],
        [278.67992698, 287.9011431 , 277.78258109, 280.42853622],
        [282.36924659, 284.81747578, 284.54612879, 286.48135453]],

       [[285.18633817, 284.11868164, 283.11520095, 285.8536749 ],
        [280.76044676, 288.19108802, 275.78053168, 283.22108938],
        [276.09858054, 275.86464566, 290.73818937, 294.44051927]],

       [[277.08265618, 275.52299133, 286.09677439, 291.89696028],
        [282.24515044, 278.96829929, 283.56997916, 276.43534198],
        [279.81312193, 282.21178967, 278.2288655 , 284.56146436]],

       [[283.07669505, 287.43909443, 278.23173183, 280.48565225],
        [287.70152491, 278.46032733, 290.3711811 , 279.88530479],
        [291.15794986, 284.56061581, 285.73853555, 278.69044711]],

       [[280.24841229, 279.76893218, 281.8246932 , 288.74111035],
        [279.0226259 , 281.80205068, 279.5120701 , 285.82918359],
        [282.0789096 , 275.44621061, 293.99793949, 283.27026802]]])
Coordinates:
  * time     (time) datetime64[us] 40B 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 24B 25.0 40.0 55.0
  * lons     (lons) float64 32B -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          Kelvin
    standard_name:  air_temperature

In [15]:
temperature_in_celsius = temperature-273.15
temperature_in_celsius

<xarray.DataArray (time: 5, lat: 3, lons: 4)> Size: 480B
array([[[ 1.97509039, -3.73938452, 10.82902461,  8.36688821],
        [ 5.52992698, 14.7511431 ,  4.63258109,  7.27853622],
        [ 9.21924659, 11.66747578, 11.39612879, 13.33135453]],

       [[12.03633817, 10.96868164,  9.96520095, 12.7036749 ],
        [ 7.61044676, 15.04108802,  2.63053168, 10.07108938],
        [ 2.94858054,  2.71464566, 17.58818937, 21.29051927]],

       [[ 3.93265618,  2.37299133, 12.94677439, 18.74696028],
        [ 9.09515044,  5.81829929, 10.41997916,  3.28534198],
        [ 6.66312193,  9.06178967,  5.0788655 , 11.41146436]],

       [[ 9.92669505, 14.28909443,  5.08173183,  7.33565225],
        [14.55152491,  5.31032733, 17.2211811 ,  6.73530479],
        [18.00794986, 11.41061581, 12.58853555,  5.54044711]],

       [[ 7.09841229,  6.61893218,  8.6746932 , 15.59111035],
        [ 5.8726259 ,  8.65205068,  6.3620701 , 12.67918359],
        [ 8.9289096 ,  2.29621061, 20.84793949, 10.12026802]]])
Coordinates:
  * time     (time) datetime64[us] 40B 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 24B 25.0 40.0 55.0
  * lons     (lons) float64 32B -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          Kelvin
    standard_name:  air_temperature

In [14]:
pressure_data = 1000.0 + 5 * np.random.randn(5, 3, 4)
pressure = xr.DataArray(
    pressure_data, coords=[times_index, lats, lons], dims=["time", "lat", "lon"]
)
pressure.attrs["units"] = "hPa"
pressure.attrs["standard_name"] = "air_pressure"

pressure

<xarray.DataArray (time: 5, lat: 3, lon: 4)> Size: 480B
array([[[ 999.22517957,  994.71237251, 1002.24125411,  998.31975249],
        [ 999.30908653,  997.30761433,  999.76758852, 1007.50894858],
        [ 991.54441808, 1006.12040442, 1006.66341393,  993.05581439]],

       [[1000.52107232, 1004.02319703,  997.10844678, 1012.68136201],
        [1006.43037385,  998.68769099,  997.6013254 ,  996.71604375],
        [ 995.36228901, 1001.92624894, 1005.73074314, 1004.84112204]],

       [[1004.9342234 ,  994.90738116, 1001.93989549, 1002.75257208],
        [ 993.54990296, 1004.30411616,  997.06143067, 1002.57683577],
        [1008.4610845 ,  994.86496527,  998.05030921,  999.14008362]],

       [[ 999.45514574, 1003.88869932, 1003.95018631,  998.34066256],
        [ 999.35576872,  994.95700254, 1002.84950818, 1005.91408436],
        [1000.97735113,  995.79319698, 1001.10324153, 1004.83198567]],

       [[ 995.5704883 , 1002.8785303 ,  998.14923618,  994.64384964],
        [1002.20216534,  998.68852741,  998.94798418,  997.5803933 ],
        [ 995.18351123, 1000.08810378,  997.15688821,  995.94103874]]])
Coordinates:
  * time     (time) datetime64[us] 40B 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 24B 25.0 40.0 55.0
  * lon      (lon) float64 32B -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          hPa
    standard_name:  air_pressure

In [16]:
#Create a Dataset Object
ds = xr.Dataset(data_vars={"Temperature": temperature,"pressure":pressure})
ds

<xarray.Dataset> Size: 1kB
Dimensions:      (time: 5, lat: 3, lons: 4, lon: 4)
Coordinates:
  * time         (time) datetime64[us] 40B 2018-01-01 2018-01-02 ... 2018-01-05
  * lat          (lat) float64 24B 25.0 40.0 55.0
  * lons         (lons) float64 32B -120.0 -100.0 -80.0 -60.0
  * lon          (lon) float64 32B -120.0 -100.0 -80.0 -60.0
Data variables:
    Temperature  (time, lat, lons) float64 480B 275.1 269.4 ... 294.0 283.3
    pressure     (time, lat, lon) float64 480B 999.2 994.7 ... 997.2 995.9

In [17]:
ds.pressure

<xarray.DataArray 'pressure' (time: 5, lat: 3, lon: 4)> Size: 480B
array([[[ 999.22517957,  994.71237251, 1002.24125411,  998.31975249],
        [ 999.30908653,  997.30761433,  999.76758852, 1007.50894858],
        [ 991.54441808, 1006.12040442, 1006.66341393,  993.05581439]],

       [[1000.52107232, 1004.02319703,  997.10844678, 1012.68136201],
        [1006.43037385,  998.68769099,  997.6013254 ,  996.71604375],
        [ 995.36228901, 1001.92624894, 1005.73074314, 1004.84112204]],

       [[1004.9342234 ,  994.90738116, 1001.93989549, 1002.75257208],
        [ 993.54990296, 1004.30411616,  997.06143067, 1002.57683577],
        [1008.4610845 ,  994.86496527,  998.05030921,  999.14008362]],

       [[ 999.45514574, 1003.88869932, 1003.95018631,  998.34066256],
        [ 999.35576872,  994.95700254, 1002.84950818, 1005.91408436],
        [1000.97735113,  995.79319698, 1001.10324153, 1004.83198567]],

       [[ 995.5704883 , 1002.8785303 ,  998.14923618,  994.64384964],
        [1002.20216534,  998.68852741,  998.94798418,  997.5803933 ],
        [ 995.18351123, 1000.08810378,  997.15688821,  995.94103874]]])
Coordinates:
  * time     (time) datetime64[us] 40B 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 24B 25.0 40.0 55.0
  * lon      (lon) float64 32B -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          hPa
    standard_name:  air_pressure

In [18]:
ds["pressure"]

<xarray.DataArray 'pressure' (time: 5, lat: 3, lon: 4)> Size: 480B
array([[[ 999.22517957,  994.71237251, 1002.24125411,  998.31975249],
        [ 999.30908653,  997.30761433,  999.76758852, 1007.50894858],
        [ 991.54441808, 1006.12040442, 1006.66341393,  993.05581439]],

       [[1000.52107232, 1004.02319703,  997.10844678, 1012.68136201],
        [1006.43037385,  998.68769099,  997.6013254 ,  996.71604375],
        [ 995.36228901, 1001.92624894, 1005.73074314, 1004.84112204]],

       [[1004.9342234 ,  994.90738116, 1001.93989549, 1002.75257208],
        [ 993.54990296, 1004.30411616,  997.06143067, 1002.57683577],
        [1008.4610845 ,  994.86496527,  998.05030921,  999.14008362]],

       [[ 999.45514574, 1003.88869932, 1003.95018631,  998.34066256],
        [ 999.35576872,  994.95700254, 1002.84950818, 1005.91408436],
        [1000.97735113,  995.79319698, 1001.10324153, 1004.83198567]],

       [[ 995.5704883 , 1002.8785303 ,  998.14923618,  994.64384964],
        [1002.20216534,  998.68852741,  998.94798418,  997.5803933 ],
        [ 995.18351123, 1000.08810378,  997.15688821,  995.94103874]]])
Coordinates:
  * time     (time) datetime64[us] 40B 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 24B 25.0 40.0 55.0
  * lon      (lon) float64 32B -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          hPa
    standard_name:  air_pressure